# todo use $NODE_IMAGE_VERSION
FROM node:18-alpine

ARG GROUP_ID
ARG USER_ID

WORKDIR /app

COPY ./app/package.json /app/package.json
COPY ./app/yarn.lock /app/yarn.lock

RUN apk update && apk upgrade

RUN apk add yarn \
    bash

COPY .docker/app/entrypoint-dev.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

EXPOSE 8080

RUN mkdir -p /.cache \
    && chown node:node /.cache

# RUN addgroup -S -g $GROUP_ID canary \
# RUN adduser -D -g "" -H --ingroup $(getent group "$GROUP_ID" | cut -d: -f1) -u $USER_ID canary
USER node

ENTRYPOINT [ "/entrypoint.sh" ]