services:
  app:
    env_file:
      - .docker/.env
    build:
      context: .
      dockerfile: .docker/app/Dockerfile-dev
      args:
        - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
      - 8081:8081